name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/Codel1417/tail_app
environment:
  sdk: '>=3.4.0-0 <4.0.0'

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cross_platform: ^3.0.1
  logging: ^1.2.0
  go_router: ^14.2.0
  vector_math: ^2.1.4 # used for joystick
  collection: ^1.18.0 # Priority Queue
  intl: #pinned to flutter version?
  uuid: ^4.4.1 # Used to generate UUID v4 ids for custom actions & move lists
  json_annotation: ^4.9.0
  crypto: ^3.0.3 # used for md5 hash checking during ota download
  #pod_player: ^0.2.2
  #tivy: ^0.1.1
  circular_buffer: ^0.11.0  # Used for serial console
  wordpress_client: ^8.5.0 # Used for tail blog
  logarte:
    git:
      url: https://github.com/Codel1417/logarte
  stack_trace: ^1.11.1
  freezed_annotation: ^2.4.3
  built_collection: ^5.1.1

  # Platform Interfaces
  device_info_plus: ^10.1.0
  wakelock_plus: ^1.2.5 # Keeps the screen awake
  file_picker: ^8.0.6 # used to manually select firmware file
  path_provider: ^2.1.3 # used to get paths for app storage and cache storage
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  back_button_interceptor: ^7.0.3 # for rejecting the back button in some places due to flutter/Go Router bugs
  url_launcher: ^6.3.0 # Open URLS in external apps
  app_settings: ^5.1.1 # Open bluetooth settings
  flutter_blue_plus: ^1.32.8
  flutter_foreground_task: ^6.5.0 # Keep the app running in the background on android
  install_referrer: # Needs gradle namespace
    git:
      url: https://github.com/undreeyyy/flutter_plugin_install_referrer
      ref: fd87e9b8f0d5ed909e929388244456f72b9b63c7
  quick_actions: ^1.0.7 # puts favorites on the home screen
  flutter_wear_os_connectivity:
    git:
      url: https://github.com/Codel1417/flutter_wear_os_connectivity
  just_audio: ^0.9.39 # Used for Sound Effects
  audio_session: ^0.1.20 # Used to configure the audio session for just_audio
  firebase_testlab_detector: ^1.0.2
  mockito: ^5.4.4
  platform: ^3.1.4

  # Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Widgets / UI
  flutter_screen_lock: ^9.1.0 # used to hide dev mode toggle
  introduction_screen: ^3.1.14 # Onboarding
  flex_color_picker: ^3.5.1
  flutter_adaptive_scaffold: ^0.1.11+1
  animate_do: ^3.3.4
  fl_chart: ^0.68.0 # Used for the battery graph
  chart_sparkline: ^1.0.15+1 # used for the move easing visual
  flutter_joystick: ^0.2.0
  multi_value_listenable_builder: ^0.0.2
  multi_listenable_builder: ^1.0.0
  flutter_markdown: ^0.7.2+1
  #video_player: ^2.8.6
  fading_edge_scrollview: ^4.1.1 # used for known gear bar
  flutter_native_splash: ^2.4.1
  lottie_native: ^0.1.3
  duration: ^3.0.13
  choice:
    git:
      url: https://github.com/davigmacode/flutter_choice
  feedback: ^3.1.0
  accessibility_tools: ^2.2.1
  awesome_snackbar_content:
    git:
      url: https://github.com/tbro2020/awesome_snackbar_content
  flutter_widget_from_html_core: ^0.15.1
  visibility_detector: ^0.4.0+2 # used on the tail blog widgets

  # Dio HTTP
  dio: ^5.5.0+1
  native_dio_adapter: ^1.3.0
  dio_smart_retry: ^6.0.0

  # Sensors
  pedometer: # Needs gradle namespace
    git:
      url: https://github.com/cph-cachet/flutter-plugins
      path: packages/pedometer
  proximity_sensor: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/flutter-proximity-sensor-plugin
  shake: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/shake
      ref: dieringe
  flutter_android_volume_keydown: # Needs gradle namespace. Only Android
    git:
      url: https://github.com/Codel1417/flutter_android_volume_keydown
      ref: feature/media_button

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # play services
  in_app_review: ^2.0.9
  upgrader: ^10.3.0

  # Spicy
  plausible_analytics: ^0.3.0 # Privacy Preserving analytics
  background_fetch: ^1.3.5
  awesome_notifications_core: ^0.9.3 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package

  # Sentry
  sentry_flutter: ^8.3.0 # Base sentry + Flutter integration
  sentry_logging: ^8.3.0 # Collects app logs
  sentry_hive: ^8.3.0 # Collects Hive storage accesses
  sentry_dio: ^8.3.0 # Collects Dio HTTP requests
  sentry_file: ^8.3.0
  feedback_sentry: # need to update for sentry
    git:
      url: https://github.com/ueman/feedback
      path: feedback_sentry
      ref: b9b78756085e0326eb745d0ba5d2e7c1f5466fe5


dev_dependencies:
  build_runner: # Required for build
  flutter_gen_runner:
  riverpod_generator: ^3.0.0-dev.6 #required for @Riverpod annotations
  json_serializable: ^6.8.0 # required for @JsonSerializable annotations
  hive_generator: ^2.0.1 # required for @HiveType annotations
  go_router_builder: ^2.7.0
  freezed: ^2.5.6

  test:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: # Dryer Lint
  riverpod_lint:

flutter:
  uses-material-design: true
  generate: true # Generate app_localizations.dart
  assets:
    - assets/
    - assets/tailcostickers/
    - CHANGELOG.md
    - PRIVACY.md

sentry: # used by the sentry-dart-plugin to upload symbols. Credentials are provided as environment variables
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true

icons_launcher:
  image_path: "assets/TC_Logo.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/TC_Logo_Transparent.png"
      adaptive_round_image: "assets/TC_Logo_Transparent.png"
      adaptive_monochrome_image: "assets/TC_Logo_Transparent_NoText_Adaptive.png"
    ios:
      enable: true

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  fullscreen: false
  color: "#ffffff"
  color_dark: "#212121"
  image: "assets/TC_Logo_Transparent.png"
  image_dark: "assets/TC_Logo_Transparent_dark.png"
  android_12:
    color: "#ffffff"
    color_dark: "#212121"
    image: "assets/TC_Logo_Transparent.png"
    image_dark: "assets/TC_Logo_Transparent_dark.png"

dependency_overrides:
  meta: any

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
  #flutter_svg: true
  #flare_flutter: true
  #rive: true
  #lottie: true