name: tail_app
description: A Cross Platform Tail Control App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/Codel1417/tail_app
environment:
  sdk: '>=3.5.0-0 <4.0.0'

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cross_platform: ^3.0.1
  logging: ^1.3.0
  go_router: ^14.8.0
  vector_math: ^2.1.4 # used for joystick
  collection: ^1.19.1 # Priority Queue
  intl: #pinned to flutter version?
  uuid: ^4.5.1 # Used to generate UUID v4 ids for custom actions & move lists
  json_annotation: ^4.9.0
  crypto: ^3.0.6 # used for md5 hash checking during ota download
  circular_buffer: ^0.12.0  # Used for serial console
  wordpress_client: ^8.5.4 # Used for tail blog
  logarte:
    git:
      url: https://github.com/Codel1417/logarte
  freezed_annotation: ^2.4.4
  built_collection: ^5.1.1

  # Platform Interfaces
  device_info_plus: ^11.3.0
  wakelock_plus: ^1.2.10 # Keeps the screen awake
  file_picker: ^8.3.7 # used to manually select firmware file
  path_provider: ^2.1.5 # used to get paths for app storage and cache storage
  package_info_plus: ^8.2.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1 # Open URLS in external apps
  flutter_blue_plus: ^1.35.2
  flutter_foreground_task: ^8.17.0 # Keep the app running in the background on android
  install_referrer: # Needs gradle namespace
    git:
      url: https://github.com/undreeyyy/flutter_plugin_install_referrer
      ref: fd87e9b8f0d5ed909e929388244456f72b9b63c7
  quick_actions: ^1.1.0 # puts favorites on the home screen
  audioplayers: ^6.1.2
  firebase_testlab_detector: ^1.0.2
  platform: ^3.1.6
  connectivity_plus: ^6.1.3

  # Watch
  is_wear: ^0.0.2+3
  watch_connectivity: ^0.2.1


  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Widgets / UI
  flutter_screen_lock: ^9.2.1 # used to hide dev mode toggle
  introduction_screen: ^3.1.16 # Onboarding
  flex_color_picker: ^3.7.0
  flutter_adaptive_scaffold: ^0.3.1+1
  animate_do: ^4.0.1
  fl_chart: ^0.70.2 # Used for the battery graph
  chart_sparkline: ^1.1.1 # used for the move easing visual
  flutter_joystick: ^0.2.1
  multi_value_listenable_builder: ^0.0.2
  flutter_markdown: ^0.7.6+2
  fading_edge_scrollview: ^4.1.1 # used for known gear bar
  flutter_native_splash: ^2.4.4
  choice:
    git:
      url: https://github.com/davigmacode/flutter_choice
  feedback: ^3.1.0
  awesome_snackbar_content: ^0.1.5
  flutter_widget_from_html_core: ^0.15.2
  visibility_detector: ^0.4.0+2 # used on the tail blog widgets
  lottie_native: ^0.1.4
  pdfx:
    git:
      url: https://github.com/Codel1417/packages.flutter
      path: packages/pdfx

  # Dio HTTP
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  native_dio_adapter: ^1.4.0

  # Sensors
  pedometer: ^4.0.2
  proximity_sensor: ^1.3.7
  shake: # Needs gradle namespace
    git:
      url: https://github.com/Codel1417/shake
      ref: dieringe
  flutter_android_volume_keydown: # Needs gradle namespace. Only Android
    git:
      url: https://github.com/Codel1417/flutter_android_volume_keydown
      ref: feature/media_button

  # Hive
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  # play services
  in_app_review: ^2.0.10
  upgrader: ^11.3.1
  google_api_availability: ^5.0.0
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  firebase_app_installations: ^0.3.2+2

  # Spicy
  plausible_analytics: ^0.3.0 # Privacy Preserving analytics
  klaviyo_flutter:
    git:
      url: https://github.com/drybnikov/klaviyo_flutter
      ref: acc2eb22f12e54e86df3541ddb23b6983ff5d2ac

  # Sentry
  sentry_flutter: ^8.13.0 # Base sentry + Flutter integration
  sentry_logging: ^8.13.0 # Collects app logs
  #sentry_hive: ^8.12.0 # Collects Hive storage accesses
  sentry_dio: ^8.13.0 # Collects Dio HTTP requests
  feedback_sentry: ^3.1.0

dev_dependencies:
  build_runner: # Required for build
  #flutter_gen_runner:
  riverpod_generator: ^2.6.4 #required for @Riverpod annotations
  json_serializable: ^6.9.4 # required for @JsonSerializable annotations
  hive_ce_generator: ^1.8.2 # required for @HiveType annotations
  go_router_builder: ^2.8.0
  freezed: ^2.5.8
  mockito: ^5.4.5

  test:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter

  flutter_lints: # Dryer Lint
  #riverpod_lint:

dependency_overrides:
  collection: 1.19.1
  pedometer:
    git:
      url: https://github.com/Codel1417/flutter-plugins
      path: packages/pedometer
  proximity_sensor:
    git:
      url: https://github.com/Codel1417/flutter-proximity-sensor-plugin
  analyzer: ^7.3.0

flutter:
  uses-material-design: true
  generate: true # Generate app_localizations.dart
  assets:
    - assets/
    - assets/tailcostickers/
    - CHANGELOG.md
    - PRIVACY.md

sentry: # used by the sentry-dart-plugin to upload symbols. Credentials are provided as environment variables
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  symbols_path: ./symbols

icons_launcher:
  image_path: "assets/TC_Logo.png"
  platforms:
    android:
      enable: true
      notification_image: "assets/TC_Logo_Transparent_NoText_small.png"
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/TC_Logo_Transparent.png"
      adaptive_round_image: "assets/TC_Logo_Transparent.png"
      adaptive_monochrome_image: "assets/TC_Logo_Transparent_NoText_Adaptive.png"
    ios:
      enable: true
      dark_path: "assets/TC_Logo_Transparent_dark.png"
      tinted_path: "assets/TC_Logo_Transparent_NoText_greyscale.png"


flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  fullscreen: false
  color: "#ffffff"
  color_dark: "#212121"
  image: "assets/TC_Logo_Transparent.png"
  image_dark: "assets/TC_Logo_Transparent_dark.png"
  android_12:
    color: "#ffffff"
    color_dark: "#212121"
    image: "assets/TC_Logo_Transparent.png"
    image_dark: "assets/TC_Logo_Transparent_dark.png"



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
  #flutter_svg: true
  #flare_flutter: true
  #rive: true
  #lottie: true
