name: 'Build Tail App builds'
description: 'Internal Action for Tail App'
inputs:
  version:
    description: 'Release Version'
    required: true
  build-number:
    description: 'Git build number'
    required: true
  android-key-properties:
    description: 'Properties file containing signing info'
    required: true
  android-key-jks:
    description: 'Base64 version of the jks file'
    required: true
  sentry-org:
    description: 'The sentry org for uploading debug symbols'
    required: true
  sentry-project:
    description: 'The sentry project for uploading debug symbols'
    required: true
  sentry-url:
    description: 'The sentry url for uploading debug symbols'
    required: false
  sentry-auth-token:
    description: 'The sentry auth token for uploading debug symbols'
    required: true
  sentry-dsn:
    description: 'The sentry dsn for sending error info'
    required: true
  build-mode:
    description: 'Build an apk or bundle'
    required: true
runs:
  using: "composite"
  steps:
    - name: Write Key Properties
      shell: bash
      if: github.event_name == 'push'
      run: echo "$ANDROID_KEY_PROPERTIES" > ./android/key.properties
      env:
        ANDROID_KEY_PROPERTIES: ${{ inputs.android-key-properties }}
    - name: Write Certificate
      shell: bash
      if: github.event_name == 'push'
      run: echo -n "$ANDROID_KEY_JKS" | base64 -d > ./android/tailCo.jks
      env:
        ANDROID_KEY_JKS: ${{ inputs.android-key-jks }}
    - name: Build APK
      if: inputs.build-mode == 'apk'
      shell: bash
      run: flutter build apk --split-debug-info=./symbols --build-number="$BUILD_NUMBER" --build-name="$VERSION" --dart-define=SENTRY_DSN="$SENTRY_DSN"
      env:
        VERSION: ${{ inputs.version }}
        BUILD_NUMBER: ${{ inputs.build-number }}
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org }}
        SENTRY_PROJECT: ${{ inputs.sentry-project }}
        SENTRY_DSN: ${{ inputs.sentry-dsn }}
        SENTRY_URL: ${{ inputs.sentry-url }}
    - name: Build AppBundle
      if: inputs.build-mode == 'bundle'
      shell: bash
      run: flutter build appbundle --split-debug-info=./symbols --build-number="$BUILD_NUMBER" --build-name="$VERSION"  --dart-define=SENTRY_DSN="$SENTRY_DSN"
      env:
        VERSION: ${{ inputs.version }}
        BUILD_NUMBER: ${{ inputs.build-number }}
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org }}
        SENTRY_PROJECT: ${{ inputs.sentry-project }}
        SENTRY_DSN: ${{ inputs.sentry-dsn }}
        SENTRY_URL: ${{ inputs.sentry-url }}
    - name: list dependencies
      shell: bash
      run: cd android && ./gradlew app:dependencies --configuration releaseCompileClasspath
    - uses: actions/upload-artifact@v4
      continue-on-error: true
      if: runner.os == 'Linux' && inputs.build-mode == 'apk'
      with:
        name: artifact-${{ runner.os }}
        path: build/app/outputs/apk
