
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    #   note the `..`, since fastlane runs in the _fastlane_ directory
    changelog = File.read("../../CHANGELOG.md")
    sync_code_signing(
      type: "appstore", 
      readonly: false, 
      api_key_path:"APPLE_SECRETS.json"
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
      entitlements_file_path: "Runner/Runner.entitlements"
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      skip_build_archive: true,
      export_team_id: "SKRSQZ43AV" ,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      xcconfig: "Flutter/Generated.xcconfig"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true, 
      changelog: changelog, 
      build_number: ENV['BUILD_NUMBER'], 
      app_version: ENV['VERSION'], 
      reject_build_waiting_for_review: true, 
      api_key_path:"APPLE_SECRETS.json"
    )
  end
end
