
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    create_keychain(
      name: "KeychainName",
      default_keychain: true,
      password: 'verySecureSecretPassword1'
    )
    unlock_keychain( # If the keychain file is located in the standard location `~/Library/Keychains`, then it is sufficient to provide the keychain file name, or file name with its suffix.
      path: "KeychainName",
      password: "verySecureSecretPassword1"
    )
    #   note the `..`, since fastlane runs in the _fastlane_ directory
    changelog = File.read("../../CHANGELOG.md")
    get_certificates(api_key_path:"APPLE_SECRETS.json")
    get_provisioning_profile(force: true, api_key_path:"APPLE_SECRETS.json")

    #get_push_certificate
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(skip_waiting_for_build_processing: true, changelog:changelog, build_number: ENV['BUILD_NUMBER'], app_version: ENV['VERSION'], reject_build_waiting_for_review: true, api_key_path:"APPLE_SECRETS.json")
  end
end
