name: "Setup Tail App builds"
description: "Internal Action for Tail App"
inputs:
  java-version:
    description: "Java version for android"
    default: "17"
  java-distribution:
    description: "Java distribution"
    default: "zulu"
  flutter-version:
    description: "Flutter Version"
    default: "3.32.4"
  ruby-version:
    description: "Ruby Version"
    default: "3.4"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      if: runner.os == 'Linux'
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: "gradle"
        cache-dependency-path: | # optional
          android/*.gradle*
          android/**/gradle-wrapper.properties
          pubspec.lock
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        cache: true
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        ruby-version: ${{ inputs.ruby-version }} # Not needed with a .ruby-version file
    - uses: maxim-lobanov/setup-xcode@v1
      if: runner.os == 'macOS'
      with:
        xcode-version: latest-stable
