name: "Setup Tail App builds"
description: "Internal Action for Tail App"
inputs:
  java-version:
    description: "Java version for android"
    default: "21"
  java-distribution:
    description: "Java distribution"
    default: "zulu"
  ruby-version:
    description: "Ruby Version"
    default: "4.0.2"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5.2.0
      if: runner.os == 'Linux'
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - uses: subosito/flutter-action@v2.23.0
      with:
        flutter-version-file: pubspec.yaml
        cache: true
    - uses: ruby/setup-ruby@v1.306.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        ruby-version: ${{ inputs.ruby-version }} # Not needed with a .ruby-version file
    - uses: maxim-lobanov/setup-xcode@v1.7.0
      if: runner.os == 'macOS'
      with:
        xcode-version: 26.4
