name: 'Setup Tail App builds'
description: 'Internal Action for Tail App'
inputs:
  java-version:
    description: 'Java version for android'
    default: '17'
  java-distribution:
    description: 'Java distribution'
    default: 'zulu'
  flutter-version:
    description: 'Flutter Version'
    default: '3.27.0'
  ruby-version:
    description: 'Ruby Version'
    default: '3.3'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      if: runner.os == 'Linux'
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        #cache: "gradle"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        cache: false
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        ruby-version: ${{ inputs.ruby-version }} # Not needed with a .ruby-version file
