name: 'Setup Tail App builds'
description: 'Internal Action for Tail App'
inputs:
  java-version:
    description: 'Java version for android'
    default: '17'
  java-distribution:
    description: 'Java distribution'
    default: 'zulu'
  flutter-version:
    description: 'Flutter Version'
    default: '3.24.1'
  ruby-version:
    description: 'Ruby Version'
    default: '3.3'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      if: runner.os == 'Linux'
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        #cache: "gradle"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        cache: false
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
        ruby-version: ${{ inputs.ruby-version }} # Not needed with a .ruby-version file
    - name: Cocoapods Cache
      uses: actions/cache@v4
      id: cocoapods-cache
      if: runner.os == 'macOS'
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Podfile lock cache
      uses: actions/cache@v4
      id: cache-podfile
      if: runner.os == 'macOS'
      with:
        path: ios/Podfile.lock
        key: ${{ runner.os }}-pods-${{ hashFiles('pubspec.lock') }}
