# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)
  desc "Deploy a new version to the Google Play"
  lane :beta do
    setup_ci if ENV['CI']
    #   note the `..`, since fastlane runs in the _fastlane_ directory
    #changelog = File.read("../../CHANGELOG.md")
    #gradle(task: "clean assembleRelease")
    changelog = changelog_from_git_commits(
        commits_count: 10, 
        pretty: "- %s", 
        date_format: "short",
        match_lightweight_tag: false, 
    )
    gradle(
        task: "wear:bundle",
        build_type: "Release",
        properties: {
          "versionCode" => ENV['BUILD_NUMBER'].to_i,
          "versionName" => ENV['VERSION'],
        }
    )
    upload_to_play_store(
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        track:"internal",
        #release_notes: changelog,
        version_code: ENV['BUILD_NUMBER'],
        version_name: ENV['VERSION'],
        json_key_data: ENV['GOOGLE_SECRETS'],
        #release_status: "draft",
    )
    upload_to_play_store(
        aab: "../build/wear/outputs/bundle/release/wear-release.aab",
        track:"wear:internal",
        #release_notes: changelog,
        version_code: ENV['BUILD_NUMBER'],
        version_name: ENV['VERSION'],
        json_key_data: ENV['GOOGLE_SECRETS'],
        #release_status: "draft",
    )
end
