# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    setup_ci if ENV['CI']
    #gradle(task: "clean assembleRelease")
    upload_to_play_store(aab: "../build/app/outputs/bundle/release/app-release.aab", track:"beta")
  end
end
